package io.xtrea.ontology.impl;

import io.xtrea.ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIlyaBot <br>
 * @version generated on Sun Apr 08 06:35:31 GMT+08:00 2018 by Jonathan
 */
public class DefaultIlyaBot extends WrappedIndividualImpl implements IlyaBot {

    public DefaultIlyaBot(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
