package io.xtrea.ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Apr 08 06:35:31 GMT+08:00 2018 by Jonathan
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Article
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTICLE.<p>
     * 
     */
    public static final OWLClass CLASS_ARTICLE = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Article"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#GameMechanism
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GAMEMECHANISM.<p>
     * 
     */
    public static final OWLClass CLASS_GAMEMECHANISM = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#GameMechanism"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#IlyaBot
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ILYABOT.<p>
     * 
     */
    public static final OWLClass CLASS_ILYABOT = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#IlyaBot"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODELINKER.<p>
     * 
     */
    public static final OWLClass CLASS_NODELINKER = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker_Quit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODELINKER_QUIT.<p>
     * 
     */
    public static final OWLClass CLASS_NODELINKER_QUIT = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker_Quit"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker_Random
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODELINKER_RANDOM.<p>
     * 
     */
    public static final OWLClass CLASS_NODELINKER_RANDOM = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#NodeLinker_Random"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Node_SelectReaction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODE_SELECTREACTION.<p>
     * 
     */
    public static final OWLClass CLASS_NODE_SELECTREACTION = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Node_SelectReaction"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Node_Successive
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODE_SUCCESSIVE.<p>
     * 
     */
    public static final OWLClass CLASS_NODE_SUCCESSIVE = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Node_Successive"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Node_Terminal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODE_TERMINAL.<p>
     * 
     */
    public static final OWLClass CLASS_NODE_TERMINAL = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Node_Terminal"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Node_TheEnd
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NODE_THEEND.<p>
     * 
     */
    public static final OWLClass CLASS_NODE_THEEND = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Node_TheEnd"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Reaction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REACTION.<p>
     * 
     */
    public static final OWLClass CLASS_REACTION = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Reaction"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Resource"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#Scenario
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIO.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIO = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#Scenario"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#ScenicNode
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENICNODE.<p>
     * 
     */
    public static final OWLClass CLASS_SCENICNODE = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#ScenicNode"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#ScenicNodeComponent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENICNODECOMPONENT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENICNODECOMPONENT = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#ScenicNodeComponent"));

    /* ***************************************************
     * Class http://xtrea.io/ontology/2018/4/ilyabot#ScenicScript
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENICSCRIPT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENICSCRIPT = factory.getOWLClass(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#ScenicScript"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#hasComponent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCOMPONENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCOMPONENT = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#hasComponent"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#hasInput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINPUT = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#hasInput"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#hasOutput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASOUTPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASOUTPUT = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#hasOutput"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#isComponentOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCOMPONENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCOMPONENTOF = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#isComponentOf"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#isMadeOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMADEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMADEOF = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#isMadeOf"));

    /* ***************************************************
     * Object Property http://xtrea.io/ontology/2018/4/ilyabot#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://xtrea.io/ontology/2018/4/ilyabot#isPartOf"));


}
